/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.chukysoelgamal;
import java.util.Random;
import java.lang.*;
import java.nio.charset.Charset;
import java.util.Base64;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JFileChooser;
import java.io.File;  
import java.io.FileReader;
import java.io.BufferedReader;
import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.PrintWriter;
import java.io.IOException;
import java.util.stream.Collectors;

/**
 *
 * @author Antoneva
 */
public class ChyKyElgamal extends javax.swing.JFrame {

    String line1="";
    /**
     * Creates new form ChyKyElgamal
     */
    public ChyKyElgamal() {
        initComponents();
        rd_td.setSelected(true);
        bt_Mahoa.setEnabled(false);
        btGiaiMa.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        So_P = new javax.swing.JTextField();
        So_A = new javax.swing.JTextField();
        So_D = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        So_X = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bt_taoKhoa = new javax.swing.JButton();
        rd_td = new javax.swing.JRadioButton();
        rd_tc = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        So_K = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        So_Y = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBanRo = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        bt_Mahoa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMaHoaBanRo = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBanMaHoaNhanDuoc = new javax.swing.JTextArea();
        btGiaiMa = new javax.swing.JButton();
        btnOpenFile = new javax.swing.JButton();
        bt_ChonLai = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chữ ký số Elgamal");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tạo khóa");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khóa công khai (p, a, d)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        So_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                So_AActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Số nguyên tố p:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Số (alpla) a:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("(d = a^x mod p) số d:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(So_D, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(So_A)
                    .addComponent(So_P)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(So_P, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(So_A, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(So_D, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khóa bí mật(x)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Số nguyên x:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(So_X, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(So_X, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        bt_taoKhoa.setBackground(new java.awt.Color(153, 153, 255));
        bt_taoKhoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_taoKhoa.setText("Tạo khóa ngẫu nhiên");
        bt_taoKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_taoKhoaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rd_td);
        rd_td.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rd_td.setText("Tạo khóa tự động");
        rd_td.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_tdActionPerformed(evt);
            }
        });

        buttonGroup1.add(rd_tc);
        rd_tc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rd_tc.setText("Tạo khóa tùy chọn");
        rd_tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_tcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(bt_taoKhoa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(rd_td)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(rd_tc)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(bt_taoKhoa)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_td)
                    .addComponent(rd_tc))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Thực hiện ký");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Số ngẫu nhiên k:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("(Y=a^k mod p) Y:");

        txtBanRo.setColumns(20);
        txtBanRo.setRows(5);
        jScrollPane1.setViewportView(txtBanRo);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Chọn file thực hiện ký:");

        bt_Mahoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_Mahoa.setText("Ký lên văn bản");
        bt_Mahoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_MahoaActionPerformed(evt);
            }
        });

        txtMaHoaBanRo.setColumns(20);
        txtMaHoaBanRo.setRows(5);
        jScrollPane2.setViewportView(txtMaHoaBanRo);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Tệp chữ ký vào file văn bản được gửi đi:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Chọn file thực hiện kiểm tra chữ ký:");

        txtBanMaHoaNhanDuoc.setColumns(20);
        txtBanMaHoaNhanDuoc.setRows(5);
        jScrollPane3.setViewportView(txtBanMaHoaNhanDuoc);

        btGiaiMa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btGiaiMa.setText("Kiểm tra chữ ký");
        btGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGiaiMaActionPerformed(evt);
            }
        });

        btnOpenFile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOpenFile.setText("Mở Tệp");
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });

        bt_ChonLai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_ChonLai.setText("Chọn lại");
        bt_ChonLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ChonLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(119, 119, 119))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(So_K, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnOpenFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_Mahoa))
                            .addComponent(So_Y)
                            .addComponent(bt_ChonLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btGiaiMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(So_K, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(So_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_ChonLai, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpenFile, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(bt_Mahoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btGiaiMa, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        jMenu4.setText("Chữ ký số Elgamal");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Hướng dẫn sử dụng");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Thông tin tác giả");
        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Code Elgamal
    private void reset(){
        So_A.setText("");
        So_D.setText("");
        So_P.setText("");
        So_K.setText("");
        So_X.setText("");
        So_Y.setText("");
    }
    
    private void So_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_So_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_So_AActionPerformed

    private void rd_tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_tcActionPerformed
           So_A.setEnabled(true);
           So_D.setEnabled(true);
           So_P.setEnabled(true);
           So_K.setEnabled(true);
           So_X.setEnabled(true);
           So_Y.setEnabled(true);
           bt_taoKhoa.setText("Tạo khóa tùy chọn");
           reset();
           bt_taoKhoa.setEnabled(true);
    }//GEN-LAST:event_rd_tcActionPerformed

    private void rd_tdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_tdActionPerformed
           So_A.setEnabled(false);
           So_D.setEnabled(false);
           So_P.setEnabled(false);
           So_K.setEnabled(false);
           So_X.setEnabled(false);
           So_Y.setEnabled(false);
           bt_taoKhoa.setText("Tạo khóa ngẫu nhiên");
           reset();
           bt_taoKhoa.setEnabled(true);
    }//GEN-LAST:event_rd_tdActionPerformed

    private void bt_taoKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_taoKhoaActionPerformed
        if (rd_td.isSelected())
            {
                // thực hiện thao tác tạo khóa ngẫu nhiên 
                reset();

                // chọn số nguyên tố ngẫu nhiên P
                EsoP = 0;
                do
                {
                    EsoP = E_ChonSoNgauNhien();
                }
                while (E_kiemTraNguyenTo(EsoP) == false);

                TaoKhoa_click();
                So_P.setText(Integer.toString(EsoP));
                So_A.setText(Integer.toString(EsoA));
                So_X.setText(Integer.toString(EsoX));
                So_D.setText(Integer.toString(EsoD));
                So_K.setText(Integer.toString(EsoK));
                So_Y.setText(Integer.toString(EsoY));
                bt_taoKhoa.setText("Tạo khóa ngẫu nhiên mới");

            }
        else
            {
                if (rd_tc.isSelected())
                {
                    // thực hiện thao tác tạo khóa tùy chọn 
                    if (So_P.getText().equals(""))
                    {
                        showMessageDialog(null, "Phải nhập số P");
                        //MessageBox.Show("Phải nhập số P ", "Thông Báo ", MessageBoxButton.OK, MessageBoxImage.Error);
                    }
                    else
                    {
                        EsoP = Integer.parseInt(So_P.getText());
                        if (E_kiemTraNguyenTo(EsoP) == false)
                        {
                            showMessageDialog(null, "Phải chọn p là số nguyên tố!");
                            //MessageBox.Show("Phải chọn P là số nguyên tố ", "Thông Báo ", MessageBoxButton.OK, MessageBoxImage.Error);
                            So_P.requestFocus();
                        }
                        else
                            if (EsoP < 1000)
                            {
                                showMessageDialog(null, "Số P quá nhỏ! Nhập số khác");
                                //MessageBox.Show("Số P quá nhỏ! Nhập số khác ", "Thông Báo ", MessageBoxButton.OK, MessageBoxImage.Error);
                                So_P.requestFocus();
                            }
                            else
                            {
                                TaoKhoa_click();
                                So_P.setText(Integer.toString(EsoP));
                                So_A.setText(Integer.toString(EsoA));
                                So_X.setText(Integer.toString(EsoX));
                                So_D.setText(Integer.toString(EsoD));
                                So_K.setText(Integer.toString(EsoK));
                                So_Y.setText(Integer.toString(EsoY));

                                bt_taoKhoa.setEnabled(false);
                                //bt_taokhoaTuychonMoi.Visible = true;
                            }
                    }
                }
            }
            danhDau = 1;
            bt_Mahoa.setEnabled(true);
    }//GEN-LAST:event_bt_taoKhoaActionPerformed

    private void bt_MahoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_MahoaActionPerformed
        String readFile = txtBanRo.getText();
        try{
        FileReader reader = new FileReader(readFile);
        BufferedReader br= new BufferedReader(reader);
        line1 =  br.lines().collect(Collectors.joining());
        br.close();
        if (danhDau != 1)
            {
                showMessageDialog(null, "Bạn chưa chọn khóa!");
            }
            else
            {
                if (txtBanRo.getText().equals(""))
                {
                    showMessageDialog(null, "Bạn chưa nhập chuỗi cần mã hóa!");
                }
                else
                {
                    if (danhDau == 1)
                    {
                        txtMaHoaBanRo.setText("");
                        String Egm_chuoiMaHoa = E_MaHoa(line1);
                        txtMaHoaBanRo.setText(Egm_chuoiMaHoa);
                        danhDau = 2;
                        bt_Mahoa.setEnabled(false);
                        btGiaiMa.setEnabled(true);
                        showMessageDialog(null, "Thực hiện ký thành công!");
                    }
                }
            }
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        try(FileWriter fw = new FileWriter(readFile, true);
            BufferedWriter bw = new BufferedWriter(fw);
             PrintWriter out = new PrintWriter(bw))
{
    out.println(txtMaHoaBanRo.getText());
} catch (IOException e) {
    //exception handling left as an exercise for the reader
}
    }//GEN-LAST:event_bt_MahoaActionPerformed

    private void btGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGiaiMaActionPerformed
       JFileChooser chooser= new JFileChooser();
            chooser.showOpenDialog(null);
            File f= chooser.getSelectedFile();
            String filename =f.getAbsolutePath();
            
            try
            {
                
                FileReader reader = new FileReader(filename);
                BufferedReader br= new BufferedReader(reader);
                String line2 =br.lines().collect(Collectors.joining());
                txtBanMaHoaNhanDuoc.setText(filename);
                String line3=E_MaHoa(line1);
                String maHoa=line1+E_MaHoa(line1);
                if(line2.equals(maHoa)){
                    JOptionPane.showMessageDialog(null,"Tài liệu gửi đến không bị chỉnh sửa gì");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Tài liệu gửi đến đã bị thay đổi");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_btGiaiMaActionPerformed

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        JFileChooser chooser= new JFileChooser();
            chooser.showOpenDialog(null);
            File f= chooser.getSelectedFile();
            String filename =f.getAbsolutePath();
            
            try
            {
                FileReader reader = new FileReader(filename);
                BufferedReader br= new BufferedReader(reader);
                txtBanRo.setText(filename);
                br.close();
                txtBanRo.requestFocus();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void bt_ChonLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ChonLaiActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bt_ChonLaiActionPerformed
    public int EsoP, EsoQ, E_So_G_A, EsoA, EsoX, EsoD, EsoK, EsoY;
    public int danhDau = 0;
    private int E_ChonSoNgauNhien()
        {
            Random rdE = new Random();
            return rdE.nextInt(2000)+1000;
        }
    private boolean E_kiemTraNguyenTo(int so_kt)
        {
            boolean kiemtra = true;
            if (so_kt == 2 || so_kt == 3)
            {
                // kiemtra = true;
                return kiemtra;
            }
            else
            {
                if (so_kt == 1 || so_kt % 2 == 0 || so_kt % 3 == 0)
                {
                    kiemtra = false;
                }
                else
                {
                    for (int i = 5; i <= Math.sqrt(so_kt); i = i + 6)
                        if (so_kt % i == 0 || so_kt % (i + 2) == 0)
                        {
                            kiemtra = false;
                            break;
                        }
                }
            }
            return kiemtra;
        } 
    private boolean E_kiemTraUocCuaSoP(int so_P, int so_Q)
        {
            boolean kt_Okie = true;
            if ((so_P - 1) % so_Q == 0)
            {
                kt_Okie = true;
            }
            else
                kt_Okie = false;
            return kt_Okie;
        }
    private boolean E_kiemTraPTSinh(int so_kt, int E_SoP_, int E_soQ_)// kiem tra phan tu sinh
        {
            boolean ktOkie = true;
            int soMu = E_SoP_ - 1 / E_soQ_;
            int ketQuaKT = E_LuyThuaModulo_(so_kt, soMu, E_SoP_);

            if (ketQuaKT != 1)
            {
                ktOkie = true;
            }
            else
            {
                if (ketQuaKT == 1) ktOkie = false;
            }
            return ktOkie;
        }
    private boolean nguyenToCungNhau(int ai, int bi)// "Hàm kiểm tra hai số nguyên tố cùng nhau"
        {
            boolean ktx_;
            // giải thuật Euclid;
            int temp;
            while (bi != 0)
            {
                temp = ai % bi;
                ai = bi;
                bi = temp;
            }
            if (ai == 1) { ktx_ = true; }
            else ktx_ = false;
            return ktx_;
        }
    private String TapP_1(int soDauVao)
        {
            String ChuoiDauRa = "";
            for (int i = 1; i < soDauVao; i++)
            {
                if (nguyenToCungNhau(soDauVao, i) == true)
                {   
                    ChuoiDauRa += Integer.toString(i)+ "#"; }
            }
            return ChuoiDauRa;
        }
    private String Tap_Qi(int soDauvao) // tìm các số khi phân tích ra thừa số của số P
        {
            String ChuoiDauRa = "";
            int soix = 2;
            while (soDauvao != 1)
            {
                if (soDauvao % soix == 0)
                {
                    ChuoiDauRa += Integer.toString(soix) + "#";
                    soDauvao = soDauvao / soix;
                }
                else soix++;
            }
            return ChuoiDauRa;
        }
    public int E_LuyThuaModulo_(int CoSo_, int SoMu_, int soModulo_)
        {

            //Sử dụng thuật toán "bình phương nhân"
            //Chuyển e sang hệ nhị phân
            int[] a = new int[100];
            int k = 0;
            do
            {
                a[k] = SoMu_ % 2;
                k++;
                SoMu_ = SoMu_ / 2;
            }
            while (SoMu_ != 0);
            //Quá trình lấy dư
            int kq = 1;

            for (int i = k - 1; i >= 0; i--)
            {
                kq = (kq * kq) % soModulo_;
                if (a[i] == 1)
                    kq = (kq * CoSo_) % soModulo_;
            }
            return kq;
        }
    private int E_tinhModulo_nghichdao(int SoNCNDn, int SoMdlm)
        {
            int kd = SoMdlm;
            int r = 1, q, y0 = 0, y1 = 1, y = 0;
            while (SoNCNDn != 0)
            {
                r = SoMdlm % SoNCNDn;
                if (r == 0)
                    break;
                else
                {
                    q = SoMdlm / SoNCNDn;
                    y = y0 - y1 * q;
                    SoMdlm = SoNCNDn;
                    SoNCNDn = r;
                    y0 = y1;
                    y1 = y;
                }
            }
            if (y >= 0)
                return y;
            else
            {
                y = kd + y;
                return y;
            }
        }
    private int E_TinhC1muxModP(int SoC1, int SomuX, int somDLP)
        {
            int kq_E_TinhC1muxModP = 1;
            for (int i = 0; i <= SomuX; i++)
            {
                kq_E_TinhC1muxModP = kq_E_TinhC1muxModP * E_tinhModulo_nghichdao(SoC1, somDLP);
            }
            return kq_E_TinhC1muxModP;
        }
    private void TaoKhoa_click()
        {
            EsoQ = E_So_G_A = EsoA = EsoX = EsoD = EsoK = 0;

            // chọn số nguyên tố ngẫu nhiên Q thỏa mãn Q là ước của P - 1;
            do
            {
                Random rdQ = new Random();
                EsoQ = rdQ.nextInt((EsoP - 1)-2)+2;
            }
            while (!E_kiemTraNguyenTo(EsoP) || !E_kiemTraUocCuaSoP(EsoP, EsoQ));
            // tìm số G để tìm số A (A là phần tử sinh): 
            do
            {
                Random rdE_So_G_A = new Random();
                E_So_G_A = rdE_So_G_A.nextInt((EsoP - 1)-2)+2;
            }
            while (!E_kiemTraPTSinh(E_So_G_A, EsoP, EsoQ));

            EsoA = E_LuyThuaModulo_(E_So_G_A, EsoP - 1 / EsoQ, EsoP); // phần tử sinh

            do
            {
                Random rdEsoX = new Random();
                EsoX = rdEsoX.nextInt((EsoP - 2)-2)+2;
            }
            while (EsoX == EsoQ || EsoX == E_So_G_A);
            // d= a^x mod P
            EsoD = E_LuyThuaModulo_(EsoA, EsoX, EsoP);// beta; d          
            do
            {
                Random rdEsoK = new Random();
                EsoK = rdEsoK.nextInt((EsoP - 2)-2)+2;
            }
            while (EsoK == EsoX || EsoK == EsoA || EsoK == EsoQ || EsoK == E_So_G_A || !nguyenToCungNhau(EsoK, EsoP - 1));
            // Tính Y = A^k mod p - Khóa công khai
            EsoY = E_LuyThuaModulo_(EsoA, EsoK, EsoP);
        }
    public String E_MaHoa(String ChuoiVao)
        {
            //Chuyen xau thanh ma Unicode         

            byte[] mhE_temp1 = ChuoiVao.getBytes(Charset.forName("UTF-8"));
            String base64 = Base64.getEncoder().encodeToString(mhE_temp1);
            
            // Chuyển xâu thành mã Unicode dạng số          
            int[] mh_temp2 = new int[base64.length()];
            for (int i = 0; i < base64.length(); i++)
            {
                mh_temp2[i] = base64.charAt(i);
                
            }

           
            //Mảng a chứa các kí tự sẽ  mã hóa
            int[] mh_temp3 = new int[mh_temp2.length];
            // thực hiện mã hóa: z = (d^k * m ) mod p

            for (int i = 0; i < mh_temp2.length; i++)
            {
                mh_temp3[i] = ((mh_temp2[i] % EsoP) * (E_LuyThuaModulo_(EsoD, EsoK, EsoP))) % EsoP;
                //txtm2.Text += mh_temp3[i].ToString()+"#";
            }
            //Chuyển sang kiểu kí tự trong bảng mã Unicode
            String str = "";
            for (int i = 0; i < mh_temp3.length; i++)
            {
                str = str + (char)mh_temp3[i];          
            }
            byte[] E_data1 = str.getBytes(Charset.forName("UTF-8"));
            String BanMaHoa = Base64.getEncoder().encodeToString(E_data1);
            return BanMaHoa;

        } 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChyKyElgamal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChyKyElgamal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChyKyElgamal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChyKyElgamal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChyKyElgamal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField So_A;
    private javax.swing.JTextField So_D;
    private javax.swing.JTextField So_K;
    private javax.swing.JTextField So_P;
    private javax.swing.JTextField So_X;
    private javax.swing.JTextField So_Y;
    private javax.swing.JButton btGiaiMa;
    private javax.swing.JButton bt_ChonLai;
    private javax.swing.JButton bt_Mahoa;
    private javax.swing.JButton bt_taoKhoa;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rd_tc;
    private javax.swing.JRadioButton rd_td;
    private javax.swing.JTextArea txtBanMaHoaNhanDuoc;
    private javax.swing.JTextArea txtBanRo;
    private javax.swing.JTextArea txtMaHoaBanRo;
    // End of variables declaration//GEN-END:variables
}
